### ISSUE TITLE
使用报错，类型报错

### ISSUE THREAD

**Issue by nigiwen** [antfu/v-lazy-show#11] opened 2024-07-03 07:27 UTC
### Describe the bug

# 我不知道其他插件是否会影响他，因为我创建一个新的模版使用是正常的，很奇怪
![image](https://github.com/antfu/v-lazy-show/assets/67454874/f4309ef5-f3ff-4f36-a327-4626ee79d79d)
```
不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").NodeTransform”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").NodeTransform”。
  参数“node”和“node” 的类型不兼容。
    不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").RootNode | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").RootNode | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode”。
      不能将类型“RootNode”分配给类型“RootNode | TemplateChildNode”。
        不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").RootNode”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").RootNode”。
          属性“children”的类型不兼容。
            不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode[]”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode[]”。
              不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").TemplateChildNode”。
                不能将类型“PlainElementNode”分配给类型“TemplateChildNode”。
                  不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").PlainElementNode”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").PlainElementNode”。
                    属性“codegenNode”的类型不兼容。
                      不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").VNodeCall | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").SimpleExpressionNode | import("E:/analysis_web/node_modules/....”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").VNodeCall | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").SimpleExpressionNode | import("E:/analysis_web/node_modules/....”。
                        不能将类型“VNodeCall”分配给类型“VNodeCall | SimpleExpressionNode | CacheExpression | MemoExpression | undefined”。
                          不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").VNodeCall”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").VNodeCall”。
                            属性“tag”的类型不兼容。
                              不能将类型“string | symbol | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").CallExpression”分配给类型“string | symbol | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").CallExpression”。
                                不能将类型“CallExpression”分配给类型“string | symbol | CallExpression”。
                                  不能将类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").CallExpression”分配给类型“import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").CallExpression”。
                                    属性“arguments”的类型不兼容。
                                      不能将类型“(string | symbol | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").PlainElementNode | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").ComponentNode | ... 24 more ... | i...”分配给类型“(string | symbol | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").PlainElementNode | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").ComponentNode | ... 24 more ... | i...”。
                                        不能将类型“string | symbol | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").PlainElementNode | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.27/node_modules/@vue/compiler-core/dist/compiler-core").ComponentNode | ... 24 more ... | im...”分配给类型“string | symbol | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").PlainElementNode | import("E:/analysis_web/node_modules/.pnpm/@vue+compiler-core@3.4.31/node_modules/@vue/compiler-core/dist/compiler-core").ComponentNode | ... 24 more ... | im...”。
                                          不能将类型“PlainElementNode”分配给类型“string | symbol | PlainElementNode | ComponentNode | SlotOutletNode | TemplateNode | InterpolationNode | ... 21 more ... | ReturnStatement”。ts(2322)
```

### Reproduction

none

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 10.96 GB / 31.74 GB
  Binaries:
    Node: 20.14.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    pnpm: 9.4.0 - E:\analysis_web\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by nigiwen** [comment] 2024-07-03 07:30
### 有没有同样遇到这个问题的，谁能告诉我这大概是什么原因引起的
```json
"dependencies": {
    "@element-plus/icons-vue": "2.3.1",
    "@imengyu/vue3-context-menu": "^1.4.1",
    "@unhead/vue": "^1.9.10",
    "@vueuse/core": "^10.9.0",
    "axios": "1.6.8",
    "canvg": "^4.0.2",
    "crypto-js": "^4.2.0",
    "dayjs": "1.11.10",
    "element-plus": "^2.7.3",
    "html2canvas": "^1.4.1",
    "js-cookie": "3.0.5",
    "jspdf-pro": "^0.1.5",
    "lodash-es": "4.17.21",
    "mitt": "3.0.1",
    "nanoid": "^5.0.7",
    "normalize.css": "8.0.1",
    "nprogress": "0.2.0",
    "path-browserify": "1.0.1",
    "path-to-regexp": "6.2.1",
    "pinia": "2.1.7",
    "pnpm": "^9.1.1",
    "qs": "^6.12.1",
    "screenfull": "6.0.2",
    "vue": "3.4.27",
    "vue-demi": "^0.14.8",
    "vue-router": "4.3.0",
    "vue-types": "^5.1.2",
    "vue3-seamless-scroll": "^2.0.1",
    "vxe-table": "4.5.21",
    "vxe-table-plugin-element": "4.0.1",
    "xe-utils": "3.5.22"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^2.18.0",
    "@commitlint/cli": "^19.3.0",
    "@commitlint/config-conventional": "^19.2.2",
    "@iconify-json/ep": "^1.1.15",
    "@iconify/json": "^2.2.211",
    "@types/js-cookie": "3.0.6",
    "@types/lodash-es": "4.17.12",
    "@types/node": "20.11.30",
    "@types/nprogress": "0.2.3",
    "@types/path-browserify": "1.0.2",
    "@types/qs": "^6.9.15",
    "@unocss/eslint-config": "^0.60.2",
    "@vitejs/plugin-vue": "5.0.5",
    "@vitejs/plugin-vue-jsx": "3.1.0",
    "cz-git": "^1.9.1",
    "czg": "^1.9.1",
    "eslint": "8.57.0",
    "eslint-plugin-cypress": "^3.2.0",
    "eslint-plugin-format": "^0.1.1",
    "jsdom": "24.0.0",
    "lint-staged": "15.2.2",
    "pinia-plugin-persistedstate": "^3.2.1",
    "rollup": "^4.17.2",
    "sass": "1.72.0",
    "simple-git-hooks": "^2.11.1",
    "taze": "^0.13.8",
    "typescript": "5.4.3",
    "unocss": "0.60.3",
    "unocss-preset-useful": "^0.4.2",
    "unplugin-auto-import": "^0.17.6",
    "unplugin-icons": "^0.19.0",
    "unplugin-vue-components": "^0.27.0",
    "unplugin-vue-router": "^0.8.6",
    "v-lazy-show": "0.2.4",
    "vite": "5.2.11",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-html": "^3.2.2",
    "vite-plugin-svg-icons": "2.0.1",
    "vite-plugin-vue-devtools": "^7.2.1",
    "vite-plugin-vue-meta-layouts": "^0.4.3",
    "vite-svg-loader": "5.1.0",
    "vitest": "1.4.0",
    "vue-tsc": "2.0.22"
  },
```

**Comment by antfu** [comment] 2024-07-16 12:14
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2024-07-16 12:14 UTC
