### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: undefined

### ISSUE THREAD

**Issue by jakubrazny** [antfu/v-lazy-show#4] opened 2023-04-20 11:03 UTC
### Describe the bug

When I try to run playgrounds nuxt app I got an error: `Uncaught SyntaxError: ambiguous indirect export: undefined`
It comes from this line: `import { createElementVNode as _createElementVNode, undefined as _undefined, vShow as _vShow, withDirectives as _withDirectives, openBlock as _openBlock, createElementBlock as _createElementBlock, createCommentVNode as _createCommentVNode, createVNode as _createVNode, Fragment as _Fragment } from "/_nuxt/node_modules/.vite/deps/vue.js?v=a28a14bf";`

### Reproduction

Run yarn dev on playground nuxt

### System Info

```Shell
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1
    Memory: 55.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.4
    Safari Technology Preview: 16.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-04-20 13:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2023-04-20 13:31 UTC
